# -*- coding: utf-8 -*-
"""Stores_sales_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt_22Z3QkB0g7VhfXbefJ-hcyhG8CYcj

Sales Forecasting using Random Forest Regression
"""

# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset
data=pd.read_csv("/content/stores_sales_forecasting.csv",encoding='latin1')

data.head()

# Check for missing values
data.isnull().sum()

""" Data Preprocessing"""

data['Order Date'] = pd.to_datetime(data['Order Date'])
data['year'] = data['Order Date'].dt.year
data['month'] = data['Order Date'].dt.month
data['day'] = data['Order Date'].dt.day
data['day_of_week'] = data['Order Date'].dt.dayofweek
data['is_weekend'] = (data['day_of_week'] >= 5).astype(int)
data['quarter'] = data['Order Date'].dt.quarter

# Define input features (X) and target variable (y)
X = data[['Quantity','Discount','Profit',
          'year','month','day','day_of_week','is_weekend','quarter']]
y = data['Sales']

X.dtypes

print(X)

print(y)

# Split data into training (80%) and testing (20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=600,max_depth=15,  min_samples_split=6,min_samples_leaf=2, random_state=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
print("R2 Score:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))

plt.scatter(y_test[:200], y_pred[:200], alpha=0.7)

plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()])



plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Random Forest - Actual vs Predicted")
plt.grid(True)
plt.show()

import pandas as pd

feature_importance = pd.Series(model.feature_importances_, index=X.columns)
feature_importance.sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.show()

"""
 “The model achieved an R² score of ~0.68, indicating good predictive performance. Feature importance analysis shows that Quantity and Profit are key drivers of sales.”"""

